

version: '3'

volumes:
  peer0.arabjo.opn.com:
  peer1.arabjo.opn.com:

networks:
  opn-bridge:
  #opn-net:
    #external: true

services:
  app-1:
    ####scale: 1
    restart: always
    image: vishal3152/kubetrain
    #environment:
      #- VAR1=VAL2
    #working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: peer node start
    #volumes:
        #- /var/run/:/host/var/run/
    ports:
      - 7051:7051
      - 8443:8443
    networks:
      - opn-bridge
    #depends_on:
      #- couchdb0
