

version: '3'

volumes:
  orderer1.opn.com:
  orderer2.opn.com:
  orderer3.opn.com:
  orderer4.opn.com:
  orderer5.opn.com:

networks:
  #opn-net:
   #external: true
  opn-bridge: 

services:
  orderer1:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    restart: always
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
    #- opn-net
    - opn-bridge
    volumes:
        - /etc/fabric-crypto/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer1.opn.com/msp:/var/hyperledger/orderer/msp
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer1.opn.com/tls/:/var/hyperledger/orderer/tls
        - orderer1.opn.com:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

  orderer2:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    restart: always
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
    #- opn-net
    - opn-bridge
    volumes:
        - /etc/fabric-crypto/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer2.opn.com/msp:/var/hyperledger/orderer/msp
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer2.opn.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.opn.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    restart: always
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
    #- opn-net
    - opn-bridge
    volumes:
        - /etc/fabric-crypto/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer3.opn.com/msp:/var/hyperledger/orderer/msp
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer3.opn.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.opn.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    restart: always
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
    #- opn-net
    - opn-bridge
    volumes:
        - /etc/fabric-crypto/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer4.opn.com/msp:/var/hyperledger/orderer/msp
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer4.opn.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.opn.com:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    restart: always
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
    #- opn-net
    - opn-bridge
    volumes:
        - /etc/fabric-crypto/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer5.opn.com/msp:/var/hyperledger/orderer/msp
        - /etc/fabric-crypto/crypto-config/ordererOrganizations/opn.com/orderers/orderer5.opn.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.opn.com:/var/hyperledger/production/orderer
    ports:
    - 11050:7050