---
- name: Compress crypto-config

  hosts: localhost
  connection: local
  #gather_facts: no
  remote_user: "{{REMOTE_USER}}"
  become: yes
  become_method: sudo
  tasks:
    - name: Compress directory locally
      archive:
        path: ../fabric-crypto/
        dest: /tmp/fabric-crypto.tar

    - name: Install pip
      apt: name=python-pip state=present

    - name: install docker
      pip: name=docker

    - name: install docker-compose
      pip: name=docker

    - name: install docker[tls]
      pip: name=docker[tls]


- name: Copy crypto material to target machine
  hosts: arabae
  #connection: local
  remote_user: "{{REMOTE_USER}}"
  become: yes
  become_method: sudo
  tasks:
    - name: Copy crypto archive to target
      copy:
        src: /tmp/fabric-crypto.tar
        dest: /tmp/
        owner: root
        group: sudo
        mode: '0644'
       # backup: yes

    - name: Create fabric-crypto directory
      file:
       path: /etc/fabric-crypto
       state: directory
       mode: "0644"

    - name: extract crypto archive to /etc/fabric-crypto
      unarchive:
        src: /tmp/fabric-crypto.tar
        dest: /etc/fabric-crypto/

    #- name: Copy docker-compose to target
    #  copy:
     #   src: ../docker-compose/{{ENTITY}}/
     #   dest: /opt/docker-compose/
      #  owner: root
      #  group: sudo
       # mode: '0644'
        #forec: yes
       # backup: yes



   # - name: Deploy stack from a compose file
   #   command: env ORG_NAME={{ORG_NAME}} IMAGE_TAG={{IMAGE_TAG}} ORG_MSP={{ORG_MSP}} docker stack deploy --compose-file /opt/docker-compose/docker-compose.yaml opnstack 
   #   become: yes

   # - name: Deploy stack from a compose file
   #   docker_stack:
   #      state: present
    #     name: opnstack
    #     compose:
     #       - /opt/docker-compose/docker-compose.yaml
     # register: output

   # - debug:
   #     var: output



# remove this after  stack deployis in place
- name: apply docker compose

  hosts: localhost
  connection: local
  #gather_facts: no
  remote_user: "{{REMOTE_USER}}"
  become: yes
  become_method: sudo
  tasks:

    - docker_compose:
        docker_host: "{{DOCKER_URL}}"
        project_src: ../docker-compose/{{ENTITY}}
        remove_orphans: yes
        state: absent
    - docker_compose:
        docker_host: "{{DOCKER_URL}}"
        project_src: ../docker-compose/{{ENTITY}}
        state: present
      register: output


   # - assert:
       # that:
       #   - "ca.ca_peer_{{ORG}}.state.running"
